### PR TITLE
[WIP] Eigen vector gmm module

### PR DESCRIPTION
**Pull request by iliaeg**

### CODE REVIEW

**Comment by awf** [comment]
Oops, sorry.   I hit "ready for review".   Trying to revert.

**Comment by awf** [comment]
LMK when you're ready for the big review.   Diffs are very large now, so it will be valuable to summarize the changes at a high level.

**Comment by iliaeg** [comment]
> Oops, sorry. I hit "ready for review". Trying to revert.
No problem, I'm almost done with this small PR.

**Comment by iliaeg** [comment]
-Implemented manualEigenVectorGmm module
-Added tests
-Finally moved gmm_eigen.h to shared

**Comment by iliaeg** [comment]
Closing PR due to obsolescence

**Pull request closed without merging**
