### PR TITLE
IO paths creating refactoring [part of #180]

### PR DESCRIPTION
**Pull request by mikhailnikolaev**
This PR contains a part of changes from the closed PR #180. It is the fourth part of the list, described here https://github.com/awf/ADBench/pull/180#issuecomment-569066919

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
This looks like exactly the right thing to do, but should we pass `static_output_dir` and `plotly_output_dir` to `print_messages`?

**Comment by mikhailnikolaev** [comment]
> This looks like exactly the right thing to do, but should we pass `static_output_dir` and `plotly_output_dir` to `print_messages`?

Actually, I think, that the refernce should be static. I know that I was the one who made it non-static, but now I've changed my mind. Firstly, all info about output and input dirs the user gets in the console when the script working. Secondly, in the future change the output dir is variative, I mean its path depend on giving (or not) `--use-file` argument. So, my proposal is to make the reference in the way it is now. Or do you disagree with me?

**Comment by tomjaguarpaw** [comment]
I think you are correct because static output is simpler and it is not critical to have it dynamic.  Let's keep things as simple as we can.

**Comment by mikhailnikolaev** [comment]
> This is great.

Thanks)

**Pull request merged**
