### PR TITLE
BA and Hand graph X-axis correcting

### PR DESCRIPTION
**Pull request by mikhailnikolaev**
Related to issue #126.

X-axes for BA and Hand graphs are corrected. Now for BA X-axis shows all scalar variable count (11n + 3m + 2p) and for Hand X-axis shows count of correspondencies. This info is extracted from data test file names, so, such files are renamed with adding respected postfixes.

# Graph examples
## Static
BA  Jacobian  - Release Graph
HAND (Complicated, Small)  Jacobian  - Release Graph
HAND (Simple, Big)  Jacobian  - Release Graph
HAND (Simple, Small)  Jacobian  - Release Graph
HAND (Complicated, Big)  Jacobian  - Release Graph

## Plotly
image
image

### CODE REVIEW

**Comment by msdmkats** [comment]
If x-axis for hand shows the number of correspondences, then, maybe we should make it say so? Because the number of independent variables is `26` for simple cases and `26 + 2 * n_correspondences` for complicated ones.

**Comment by mikhailnikolaev** [comment]
> If x-axis for hand shows the number of correspondences, then, maybe we should make it say so? Because the number of independent variables is `26` for simple cases and `26 + 2 * n_correspondences` for complicated ones.

It looks reasonable. I've done this

**Comment by tomjaguarpaw** [comment]
I'm not familiar with HAND, but does Manual really not get slower for bigger problem sizes?

**Comment by mikhailnikolaev** [comment]
> I'm not familiar with HAND, but does Manual really not get slower for bigger problem sizes?

It does, but in relation to others tools slowdown doesn't look very significant. I mean, it's very hard to notice deceleration in such a scale. You can look at plots from PR #105, for example. You will see the same situation, but that PR was closed about a month ago, so, there is not possibility that the current PR could break graph plotting for Manual HAND.

**Pull request merged**
